### ISSUE TITLE
Documentation for "development" type mentions non-existent deployment type

### ISSUE THREAD

**Issue by reftel** [Skatteetaten/aurora#74]
From https://github.com/Skatteetaten/aurora/blob/master/docs/documentation/aurora-config.md#development :

> The development deployment type is similar to the release deployment type but it will not deploy a prebuilt image and instead create an OpenShift BuildConfig that can be used to build ad hoc images from DeliveryBundles from your local development machine.

There is no `release` deployment type listed. Should that have been "the deploy deployment type"?

**Comment by reftel** [comment]
Ping @stromland

**Comment by stromland** [comment]
"the deploy deployment type" is correct. Updated in PR #79
